### PR TITLE
Fix: lock caching is broken when using different timeouts for the same path

### LINKED ISSUE #5: Caching does not take timeout into account
This means your codebase can't sometimes take a lock in a blocking way and sometimes in a non-blocking way.
```python
>>> lock1 = locket.lock_file("/tmp/xxx.lock")
>>> lock2 = locket.lock_file("/tmp/xxx.lock", timeout=0)
>>> lock1 is lock2
True
>>> lock2.acquire()
>>> lock2.acquire()
[ hangs until Ctrl-C ]
```

The solution would be to allow overriding timeout on acquire() instead. What do you think @mwilliamson?

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Not sure what needs to be done for Travis to like the tox setup here. @mwilliamson

**Comment by mwilliamson** [comment]
Thanks for the pull request!

This broadly looks fine to me. A couple of thoughts:

* Is the lock mixin necessary? It seems to me that the only class that needs to be a context manager is the one that actually gets returned to the caller i.e. `_Locker`.
* Rather than asserting identity on locks, the better thing to do would probably be to describe the actual behaviour we're interested in i.e. whether locks are re-entrant. It's my original mistake though, so I'm happy for this to be merged and I'll tidy up the tests.

> Not sure what needs to be done for Travis to like the tox setup here.
>
> Edit: I removed tox from the Travis-Ci config and used nosetests there instead.

I've updated master with a fix to the Travis configuration.

**Comment by pitrou** [comment]
> Is the lock mixin necessary? It seems to me that the only class that needs to be a context manager is the one that actually gets returned to the caller i.e. _Locker.

I think ideally locket should grow a more classical lock interface, where the timeout argument is part of the `acquire` call rather the constructor.

>  It's my original mistake though, so I'm happy for this to be merged and I'll tidy up the tests.

Thanks. I think it's better indeed :-)

**Comment by mwilliamson** [comment]
> I think ideally locket should grow a more classical lock interface, where the timeout argument is part of the `acquire` call rather the constructor.

I don't necessarily disagree, but that feels like a separate issue from whether the mixin is necessary (and indeed, separate from this particular issue overall).

**Comment by mwilliamson** [comment]
As an aside: my impression has always been that there are plenty of other file locking libraries available for Python that are more popular, and that this library's usage was negligible. Mind if I ask how you found this one, and why you chose it?

**Comment by pitrou** [comment]
I was looking for a cross-platform library that's crash-resistent, and `locket` seems to be the only one.

**Comment by mwilliamson** [comment]
I haven't looked since I wrote locket, but the others I found at the time had one flaw or another for my particular use-case. Do you remember how you found it? I've never seen locket in any Google search results.

Thanks for the changes, I think this is good to merge.

**Comment by pitrou** [comment]
> Do you remember how you found it?

Yes. I searched for file locking on PyPI and chose the only library that seemed to fit the bill. Disappointingly, most Python file locking libraries seem not to bother being crash-resistent.

**Pull request merged**
