### PR TITLE
Lock the locks

### PR DESCRIPTION
**Pull request by mrocklin**
This adds a `threading.Lock` on top of `_LockFile` so that `locket` locks may be used in multi-threaded applications.

### CODE REVIEW

**Comment by mrocklin** [comment]
Now passing tests.  Thanks for `locket` btw @mwilliamson .  It's a sweet little library.

**Comment by mwilliamson** [comment]
Thanks for the kind words! I didn't even know anybody used this.

Thanks also for the pull request, this looks sensible to me. A couple of thoughts:

* Do you think there are any situations where the previous behaviour is what's desired? What happens in multi-threaded applications before this change?

* I think a naked `raise` is probably more appropriate in `acquire` i.e.

  ```python
      except:
          self._thread_lock.release()
          raise
  ```

**Comment by mrocklin** [comment]
>  I didn't even know anybody used this.

Yeah, I was surprised to see that it was unstarred/forked on github.  I couldn't find anything cleaner/saner online though.  Is there something else I should use?

> Do you think there are any situations where the previous behaviour is what's desired? What happens in multi-threaded applications before this change?

`_file` found itself set to `None` at inappropriate times

> I think a naked `raise` is probably more appropriate in `acquire` i.e.

Ah yes, the naked raise is cleaner.  Fixed.

**Comment by mrocklin** [comment]
Any more feedback on this?  Also, how is your release cycle these days?

**Comment by mwilliamson** [comment]
Sorry for the delay, I was just thinking about this a bit more. Specifically, what the behaviour should be with respect to multiple threads, or even multiple attempts to lock in the same thread. At the moment, (aside from the race condition you've hit), I believe this behaves as flock i.e. once the lock has been acquired, any further attempts to acquire will succeed. Further, the lock can be released with just a single call to release, regardless of how many times it was acquired.

With your change, you get the existing behaviour if you create new lock objects for the same path. However, if you reuse the same lock object, the second attempt to acquire will block until the first releases. Locking just for the duration of the `acquire` and `release` methods would preserve the existing behaviour while removing the race.

Also, I'd need to check whether the Windows behaviour is the same.

Apologies for making this go on a bit! Just trying to make sure that the behaviour is consistent.

As for release cycle: I'll release whenever changes are made, since it only takes a moment to upload to PyPI.

**Comment by mwilliamson** [comment]
Sorry, I meant fcntl rather than flock. Which is an especially foolish mistake to make given the wild difference in semantics.

**Comment by mwilliamson** [comment]
No, wait, I was right the first time. The Python module is `fcntl`, but `flock` is the actual function that is used. Although it might actually be emulated using `fcntl` on some systems.

Gah, I hate concurrency. I'm going to stop posting poorly thought-out replies and actually do some reading. Apologies for the noise!

**Comment by mrocklin** [comment]
Ah, I had assumed that multiple acquires of the same lock would block.  Happy to change things around.  Presumably we would just want certain code blocks to be atomic if you'd like to preserve the original semantics. 

In regards to the slip up I was too ignorant to notice :)

**Comment by mwilliamson** [comment]
Okey doke, for the sake of simplicity (and the corresponding ability to be at least somewhat confident that we're implementing consistent/correct behaviour), I'd suggest:

* We make the lock non-re-entrant i.e. if any thread attempts to acquire an already-acquired thread, it should block until the owning thread releases the lock

* Reusing the same lock object should be the same as calling `lock_file` with the same path (and the simplest implementation is probably to actually reuse the lock object for each path).

Your changes already do the first part, but would need tweaking for the second part. It would also be nice to get a test or two just to confirm this behaviour. If those changes sound sensible, you're more than welcome to have a crack at them. Otherwise, I'll take a look when I get a chance (hopefully tomorrow or the day after).

Also, I'll bump the version to 0.2.0 since this is potentially a breaking change, and actually document the behaviour in `README.md`.

**Comment by mrocklin** [comment]
> If those changes sound sensible, you're more than welcome to have a crack at them. Otherwise, I'll take a look when I get a chance (hopefully tomorrow or the day after).

I'm a bit saturated this week.  More than happy to let you do all the hard work :)

**Comment by mwilliamson** [comment]
> I'm a bit saturated this week. More than happy to let you do all the hard work :)

Heh, thanks! I think what I've got on my [`threading`](https://github.com/mwilliamson/locket.py/tree/threading) branch should work, which includes a couple of tests to spell out at least some of the behaviour. Do you want to give it a whirl to see if it works for you before I publish to PyPI?

**Comment by mrocklin** [comment]
Sorry to be silent here.  Other things popped up.  I'll probably be back on a workflow that stresses this by early next week (possibly sooner.)

**Comment by mrocklin** [comment]
I've used your threading branch and have had no problems with it.  My concurrent workflow is happy.

**Comment by mwilliamson** [comment]
Excellent, I'll add some documentation on the new behaviour when I get a chance, and then upload 0.2 to PyPI. Thanks!

**Comment by mwilliamson** [comment]
I've just uploaded 0.2.0 to PyPI, thanks for the suggestion/code!

**Comment by mrocklin** [comment]
Woot.  Thanks for resolving this.

**Pull request merged**
